### PR TITLE
Adds CODEOWNERS file

### PR DESCRIPTION
**Pull request by bdarfler**

### CODE REVIEW

**Comment by vreynolds** [comment]
Is this different from https://github.com/honeycombio/libhoney-go/blob/main/CODEOWNERS?

**Comment by MikeGoldsmith** [comment]
Yeah, the one you linked to is in the wrong place / name.

@bdarfler could you remove the old file as part of this PR please?

**Review by MikeGoldsmith — APPROVED** [review]

**Comment by bdarfler** [comment]
@MikeGoldsmith @vreynolds updated to remove the incorrect file

**Review by robbkidd — APPROVED** [review]
tenor-177913847

**Pull request merged**
